-- ============================================================
-- Add dynamic DCC team-player memberships.
--
-- Purpose:
--   Represent which active DCC players currently belong to each
--   playing team/group without assigning a player permanently to
--   one team.
--
-- A player may belong to multiple teams simultaneously.
--
-- Membership history is preserved:
--   - adding a player creates an Active membership;
--   - removing a player closes that membership;
--   - re-adding the player later creates a new membership period.
--
-- Authority:
--   - Super Admins may manage membership for any team.
--   - Active Team Admins may manage membership only for teams
--     they actively administer.
--
-- Team membership is NOT an eligibility rule. It will be used
-- primarily for team organisation and availability targeting.
-- ============================================================


-- ============================================================
-- Table
-- ============================================================

create table public.team_player_memberships (
  membership_id bigint
    generated by default as identity
    primary key,

  team_id text
    not null
    references public.teams(team_id),

  player_id text
    not null
    references public.players(player_id),

  active boolean
    not null
    default true,

  assigned_at timestamp with time zone
    not null
    default now(),

  assigned_by uuid
    not null
    references auth.users(id),

  removed_at timestamp with time zone,

  removed_by uuid
    references auth.users(id),

  created_at timestamp with time zone
    not null
    default now(),

  constraint team_player_memberships_removal_state_check
    check (
      (
        active = true
        and removed_at is null
        and removed_by is null
      )
      or
      (
        active = false
        and removed_at is not null
        and removed_by is not null
      )
    )
);


-- Only one currently-active membership may exist for the same
-- player and team. Historical closed membership periods remain.
create unique index team_player_memberships_one_active_membership
on public.team_player_memberships (
  team_id,
  player_id
)
where active = true;


create index team_player_memberships_team_active_idx
on public.team_player_memberships (
  team_id,
  active
);


create index team_player_memberships_player_active_idx
on public.team_player_memberships (
  player_id,
  active
);


-- ============================================================
-- Row Level Security
--
-- Direct client writes are deliberately not permitted.
-- Membership changes must pass through the audited authority
-- functions defined later in this migration.
-- ============================================================

alter table public.team_player_memberships
enable row level security;


-- Active authenticated DCC accounts may read team membership.
--
-- This supports team pages and future availability workflows
-- without granting direct mutation rights.
create policy
  "Active DCC users can read team player memberships"
on public.team_player_memberships
for select
to authenticated
using (
  exists (
    select 1
    from public.user_profiles
    where user_profiles.user_id = auth.uid()
      and user_profiles.status = 'Active'
  )
);


-- ============================================================
-- Authority helper
--
-- Determine whether the current authenticated user may manage
-- membership for a particular team.
--
-- Super Admin:
--   may manage every team.
--
-- Team Admin:
--   may manage only a team for which they have an active
--   team_admin_assignments row.
-- ============================================================

create or replace function public.can_manage_team_membership(
  target_team_id text
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select
    auth.uid() is not null
    and nullif(trim(target_team_id), '') is not null
    and exists (
      select 1
      from public.user_profiles
      where user_profiles.user_id = auth.uid()
        and user_profiles.status = 'Active'
        and (
          user_profiles.account_role = 'Super Admin'
          or exists (
            select 1
            from public.team_admin_assignments
            where team_admin_assignments.user_id = auth.uid()
              and team_admin_assignments.team_id =
                trim(target_team_id)
              and team_admin_assignments.active = true
          )
        )
    );
$$;


-- ============================================================
-- Add player to team membership
-- ============================================================

create or replace function public.add_player_to_team(
  target_team_id text,
  target_player_id text
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  new_membership_id bigint;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  if nullif(trim(target_team_id), '') is null then
    raise exception 'A team is required';
  end if;

  if nullif(trim(target_player_id), '') is null then
    raise exception 'A player is required';
  end if;


  -- ----------------------------------------------------------
  -- Validate team
  -- ----------------------------------------------------------

  perform 1
  from public.teams
  where team_id = trim(target_team_id);

  if not found then
    raise exception
      'Team % does not exist',
      trim(target_team_id);
  end if;


  -- ----------------------------------------------------------
  -- Validate authority
  -- ----------------------------------------------------------

  if not public.can_manage_team_membership(
    trim(target_team_id)
  ) then
    raise exception
      'You are not authorised to manage membership for this team';
  end if;


  -- ----------------------------------------------------------
  -- Validate player
  --
  -- Inactive players cannot be newly added to a playing group.
  -- ----------------------------------------------------------

  perform 1
  from public.players
  where player_id = trim(target_player_id)
    and active = true;

  if not found then
    raise exception
      'Player % does not exist or is inactive',
      trim(target_player_id);
  end if;


  -- ----------------------------------------------------------
  -- Prevent duplicate active membership
  -- ----------------------------------------------------------

  perform 1
  from public.team_player_memberships
  where team_id = trim(target_team_id)
    and player_id = trim(target_player_id)
    and active = true;

  if found then
    raise exception
      'Player % is already an active member of team %',
      trim(target_player_id),
      trim(target_team_id);
  end if;


  -- ----------------------------------------------------------
  -- Create a new membership period.
  --
  -- If this player belonged to the team historically, the old
  -- closed row remains untouched and this creates a new period.
  -- ----------------------------------------------------------

  insert into public.team_player_memberships (
    team_id,
    player_id,
    active,
    assigned_at,
    assigned_by
  )
  values (
    trim(target_team_id),
    trim(target_player_id),
    true,
    now(),
    auth.uid()
  )
  returning membership_id
  into new_membership_id;

  return new_membership_id;
end;
$$;


-- ============================================================
-- Remove player from team membership
--
-- Historical membership is preserved. The row is closed rather
-- than deleted.
-- ============================================================

create or replace function public.remove_player_from_team(
  target_team_id text,
  target_player_id text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_membership_id bigint;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  if nullif(trim(target_team_id), '') is null then
    raise exception 'A team is required';
  end if;

  if nullif(trim(target_player_id), '') is null then
    raise exception 'A player is required';
  end if;


  -- ----------------------------------------------------------
  -- Validate authority
  -- ----------------------------------------------------------

  if not public.can_manage_team_membership(
    trim(target_team_id)
  ) then
    raise exception
      'You are not authorised to manage membership for this team';
  end if;


  -- ----------------------------------------------------------
  -- Lock and locate the active membership
  -- ----------------------------------------------------------

  select membership_id
  into target_membership_id
  from public.team_player_memberships
  where team_id = trim(target_team_id)
    and player_id = trim(target_player_id)
    and active = true
  for update;

  if not found then
    raise exception
      'Player % is not an active member of team %',
      trim(target_player_id),
      trim(target_team_id);
  end if;


  -- ----------------------------------------------------------
  -- Close the membership period
  -- ----------------------------------------------------------

  update public.team_player_memberships
  set
    active = false,
    removed_at = now(),
    removed_by = auth.uid()
  where membership_id = target_membership_id;
end;
$$;


-- ============================================================
-- Table permissions
--
-- authenticated receives SELECT only.
--
-- There are deliberately no INSERT / UPDATE / DELETE grants.
-- All membership mutations must use the controlled functions.
-- ============================================================

revoke all
on table public.team_player_memberships
from public;

revoke all
on table public.team_player_memberships
from anon;

revoke all
on table public.team_player_memberships
from authenticated;

grant select
on table public.team_player_memberships
to authenticated;


-- ============================================================
-- Function permissions
-- ============================================================

revoke all
on function public.can_manage_team_membership(text)
from public;

grant execute
on function public.can_manage_team_membership(text)
to authenticated;


revoke all
on function public.add_player_to_team(text, text)
from public;

grant execute
on function public.add_player_to_team(text, text)
to authenticated;


revoke all
on function public.remove_player_from_team(text, text)
from public;

grant execute
on function public.remove_player_from_team(text, text)
to authenticated;