create table public.user_profiles (
    user_id uuid primary key references auth.users(id) on update cascade on delete cascade,
    player_id text unique references public.players(player_id) on update cascade on delete restrict,
    account_role text not null default 'Player',
    status text not null default 'Invited',
    display_name text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint user_profiles_account_role_check
        check (account_role in ('Player', 'Super Admin')),

    constraint user_profiles_status_check
        check (status in ('Invited', 'Active', 'Disabled'))
);

create table public.captain_assignments (
    assignment_id bigint generated by default as identity primary key,
    user_id uuid not null references public.user_profiles(user_id) on update cascade on delete cascade,
    team_id text not null references public.teams(team_id) on update cascade on delete restrict,
    active boolean not null default true,
    assigned_at timestamptz not null default now(),
    removed_at timestamptz,

    constraint captain_assignments_removed_at_check
        check (
            (active = true and removed_at is null)
            or
            (active = false)
        )
);

create unique index captain_assignments_one_active_team_per_user
    on public.captain_assignments (user_id, team_id)
    where active = true;

alter table public.user_profiles enable row level security;
alter table public.captain_assignments enable row level security;