


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "public";


ALTER SCHEMA "public" OWNER TO "pg_database_owner";


COMMENT ON SCHEMA "public" IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."competitions" (
    "competition_id" "text" NOT NULL,
    "season" integer NOT NULL,
    "competition_name" "text" NOT NULL,
    "competition_type" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "competitions_competition_type_check" CHECK (("competition_type" = ANY (ARRAY['League'::"text", 'Cup'::"text"])))
);


ALTER TABLE "public"."competitions" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."league_standings" (
    "standing_id" bigint NOT NULL,
    "competition_id" "text" NOT NULL,
    "team_name" "text" NOT NULL,
    "played" integer DEFAULT 0 NOT NULL,
    "won" integer DEFAULT 0 NOT NULL,
    "tied" integer DEFAULT 0 NOT NULL,
    "lost" integer DEFAULT 0 NOT NULL,
    "no_result" integer DEFAULT 0 NOT NULL,
    "points" integer DEFAULT 0 NOT NULL,
    "net_run_rate" numeric(6,3),
    "position" integer,
    "status" "text",
    "is_dunmurry" boolean DEFAULT false NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."league_standings" OWNER TO "postgres";


ALTER TABLE "public"."league_standings" ALTER COLUMN "standing_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."league_standings_standing_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."match_stories" (
    "story_id" bigint NOT NULL,
    "match_id" "text" NOT NULL,
    "team_id" "text",
    "story" "text" NOT NULL,
    "author_label" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."match_stories" OWNER TO "postgres";


ALTER TABLE "public"."match_stories" ALTER COLUMN "story_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."match_stories_story_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."match_team_entries" (
    "source_match_id" "text" NOT NULL,
    "match_id" "text" NOT NULL,
    "team_id" "text" NOT NULL,
    "competition_id" "text" NOT NULL,
    "opponent_id" "text",
    "opponent_display_name" "text" NOT NULL,
    "result" "text",
    "scheduled_overs" integer,
    "revised_overs" integer,
    "dcc_score" integer,
    "dcc_wickets" integer,
    "dcc_balls" integer,
    "opponent_score" integer,
    "opponent_wickets" integer,
    "opponent_balls" integer,
    "match_notes" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "match_team_entries_dcc_balls_check" CHECK ((("dcc_balls" IS NULL) OR ("dcc_balls" >= 0))),
    CONSTRAINT "match_team_entries_dcc_score_check" CHECK ((("dcc_score" IS NULL) OR ("dcc_score" >= 0))),
    CONSTRAINT "match_team_entries_dcc_wickets_check" CHECK ((("dcc_wickets" IS NULL) OR (("dcc_wickets" >= 0) AND ("dcc_wickets" <= 10)))),
    CONSTRAINT "match_team_entries_opponent_balls_check" CHECK ((("opponent_balls" IS NULL) OR ("opponent_balls" >= 0))),
    CONSTRAINT "match_team_entries_opponent_score_check" CHECK ((("opponent_score" IS NULL) OR ("opponent_score" >= 0))),
    CONSTRAINT "match_team_entries_opponent_wickets_check" CHECK ((("opponent_wickets" IS NULL) OR (("opponent_wickets" >= 0) AND ("opponent_wickets" <= 10)))),
    CONSTRAINT "match_team_entries_result_check" CHECK ((("result" IS NULL) OR ("result" = ANY (ARRAY['Won'::"text", 'Lost'::"text", 'Tied'::"text", 'Draw'::"text", 'No Result'::"text", 'Abandoned'::"text", 'Awarded'::"text", 'Forfeit'::"text"])))),
    CONSTRAINT "match_team_entries_revised_overs_check" CHECK ((("revised_overs" IS NULL) OR ("revised_overs" >= 0))),
    CONSTRAINT "match_team_entries_scheduled_overs_check" CHECK ((("scheduled_overs" IS NULL) OR ("scheduled_overs" >= 0)))
);


ALTER TABLE "public"."match_team_entries" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."matches" (
    "match_id" "text" NOT NULL,
    "season" integer NOT NULL,
    "match_date" "date",
    "fixture_label" "text" NOT NULL,
    "status" "text" DEFAULT 'Completed'::"text" NOT NULL,
    "is_internal_dcc_match" boolean DEFAULT false NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "matches_status_check" CHECK (("status" = ANY (ARRAY['Scheduled'::"text", 'Completed'::"text", 'Awarded'::"text", 'Forfeit'::"text", 'Cancelled'::"text", 'Abandoned'::"text", 'No Result'::"text"])))
);


ALTER TABLE "public"."matches" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."opponents" (
    "opponent_id" "text" NOT NULL,
    "opponent_name" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."opponents" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."player_match_performances" (
    "performance_id" "text" NOT NULL,
    "source_match_id" "text" NOT NULL,
    "player_id" "text" NOT NULL,
    "team_id" "text" NOT NULL,
    "batted" boolean DEFAULT false NOT NULL,
    "batting_position" integer,
    "runs" integer,
    "balls_faced" integer,
    "fours" integer,
    "sixes" integer,
    "dismissal_type" "text",
    "is_not_out" boolean,
    "bowled" boolean DEFAULT false NOT NULL,
    "bowling_balls" integer,
    "maidens" integer,
    "runs_conceded" integer,
    "wickets" integer,
    "wides" integer,
    "no_balls" integer,
    "wickets_bowled" integer,
    "wickets_caught" integer,
    "wickets_lbw" integer,
    "wickets_stumped" integer,
    "wickets_caught_and_bowled" integer,
    "wickets_hit_wicket" integer,
    "catches" integer,
    "stumpings" integer,
    "run_outs" integer,
    "performance_notes" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "player_match_performances_balls_faced_check" CHECK ((("balls_faced" IS NULL) OR ("balls_faced" >= 0))),
    CONSTRAINT "player_match_performances_batting_position_check" CHECK ((("batting_position" IS NULL) OR (("batting_position" >= 1) AND ("batting_position" <= 11)))),
    CONSTRAINT "player_match_performances_bowling_balls_check" CHECK ((("bowling_balls" IS NULL) OR ("bowling_balls" >= 0))),
    CONSTRAINT "player_match_performances_catches_check" CHECK ((("catches" IS NULL) OR ("catches" >= 0))),
    CONSTRAINT "player_match_performances_fours_check" CHECK ((("fours" IS NULL) OR ("fours" >= 0))),
    CONSTRAINT "player_match_performances_maidens_check" CHECK ((("maidens" IS NULL) OR ("maidens" >= 0))),
    CONSTRAINT "player_match_performances_no_balls_check" CHECK ((("no_balls" IS NULL) OR ("no_balls" >= 0))),
    CONSTRAINT "player_match_performances_run_outs_check" CHECK ((("run_outs" IS NULL) OR ("run_outs" >= 0))),
    CONSTRAINT "player_match_performances_runs_check" CHECK ((("runs" IS NULL) OR ("runs" >= 0))),
    CONSTRAINT "player_match_performances_runs_conceded_check" CHECK ((("runs_conceded" IS NULL) OR ("runs_conceded" >= 0))),
    CONSTRAINT "player_match_performances_sixes_check" CHECK ((("sixes" IS NULL) OR ("sixes" >= 0))),
    CONSTRAINT "player_match_performances_stumpings_check" CHECK ((("stumpings" IS NULL) OR ("stumpings" >= 0))),
    CONSTRAINT "player_match_performances_wickets_bowled_check" CHECK ((("wickets_bowled" IS NULL) OR ("wickets_bowled" >= 0))),
    CONSTRAINT "player_match_performances_wickets_caught_and_bowled_check" CHECK ((("wickets_caught_and_bowled" IS NULL) OR ("wickets_caught_and_bowled" >= 0))),
    CONSTRAINT "player_match_performances_wickets_caught_check" CHECK ((("wickets_caught" IS NULL) OR ("wickets_caught" >= 0))),
    CONSTRAINT "player_match_performances_wickets_check" CHECK ((("wickets" IS NULL) OR (("wickets" >= 0) AND ("wickets" <= 10)))),
    CONSTRAINT "player_match_performances_wickets_hit_wicket_check" CHECK ((("wickets_hit_wicket" IS NULL) OR ("wickets_hit_wicket" >= 0))),
    CONSTRAINT "player_match_performances_wickets_lbw_check" CHECK ((("wickets_lbw" IS NULL) OR ("wickets_lbw" >= 0))),
    CONSTRAINT "player_match_performances_wickets_stumped_check" CHECK ((("wickets_stumped" IS NULL) OR ("wickets_stumped" >= 0))),
    CONSTRAINT "player_match_performances_wides_check" CHECK ((("wides" IS NULL) OR ("wides" >= 0)))
);


ALTER TABLE "public"."player_match_performances" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."player_profiles" (
    "player_id" "text" NOT NULL,
    "role" "text",
    "photo_url" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."player_profiles" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."players" (
    "player_id" "text" NOT NULL,
    "player_name" "text" NOT NULL,
    "player_slug" "text",
    "active" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."players" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."seasons" (
    "season" integer NOT NULL,
    "is_current" boolean DEFAULT false NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."seasons" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."team_profiles" (
    "team_id" "text" NOT NULL,
    "season" integer NOT NULL,
    "logo_url" "text",
    "achievement" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."team_profiles" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."teams" (
    "team_id" "text" NOT NULL,
    "team_name" "text" NOT NULL,
    "display_order" integer,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."teams" OWNER TO "postgres";


ALTER TABLE ONLY "public"."competitions"
    ADD CONSTRAINT "competitions_pkey" PRIMARY KEY ("competition_id");



ALTER TABLE ONLY "public"."competitions"
    ADD CONSTRAINT "competitions_season_competition_name_key" UNIQUE ("season", "competition_name");



ALTER TABLE ONLY "public"."league_standings"
    ADD CONSTRAINT "league_standings_competition_id_team_name_key" UNIQUE ("competition_id", "team_name");



ALTER TABLE ONLY "public"."league_standings"
    ADD CONSTRAINT "league_standings_pkey" PRIMARY KEY ("standing_id");



ALTER TABLE ONLY "public"."match_stories"
    ADD CONSTRAINT "match_stories_match_id_team_id_key" UNIQUE ("match_id", "team_id");



ALTER TABLE ONLY "public"."match_stories"
    ADD CONSTRAINT "match_stories_pkey" PRIMARY KEY ("story_id");



ALTER TABLE ONLY "public"."match_team_entries"
    ADD CONSTRAINT "match_team_entries_match_id_team_id_key" UNIQUE ("match_id", "team_id");



ALTER TABLE ONLY "public"."match_team_entries"
    ADD CONSTRAINT "match_team_entries_pkey" PRIMARY KEY ("source_match_id");



ALTER TABLE ONLY "public"."matches"
    ADD CONSTRAINT "matches_pkey" PRIMARY KEY ("match_id");



ALTER TABLE ONLY "public"."opponents"
    ADD CONSTRAINT "opponents_opponent_name_key" UNIQUE ("opponent_name");



ALTER TABLE ONLY "public"."opponents"
    ADD CONSTRAINT "opponents_pkey" PRIMARY KEY ("opponent_id");



ALTER TABLE ONLY "public"."player_match_performances"
    ADD CONSTRAINT "player_match_performances_pkey" PRIMARY KEY ("performance_id");



ALTER TABLE ONLY "public"."player_match_performances"
    ADD CONSTRAINT "player_match_performances_source_match_id_player_id_key" UNIQUE ("source_match_id", "player_id");



ALTER TABLE ONLY "public"."player_profiles"
    ADD CONSTRAINT "player_profiles_pkey" PRIMARY KEY ("player_id");



ALTER TABLE ONLY "public"."players"
    ADD CONSTRAINT "players_pkey" PRIMARY KEY ("player_id");



ALTER TABLE ONLY "public"."players"
    ADD CONSTRAINT "players_player_name_key" UNIQUE ("player_name");



ALTER TABLE ONLY "public"."players"
    ADD CONSTRAINT "players_player_slug_key" UNIQUE ("player_slug");



ALTER TABLE ONLY "public"."seasons"
    ADD CONSTRAINT "seasons_pkey" PRIMARY KEY ("season");



ALTER TABLE ONLY "public"."team_profiles"
    ADD CONSTRAINT "team_profiles_pkey" PRIMARY KEY ("team_id", "season");



ALTER TABLE ONLY "public"."teams"
    ADD CONSTRAINT "teams_pkey" PRIMARY KEY ("team_id");



ALTER TABLE ONLY "public"."teams"
    ADD CONSTRAINT "teams_team_name_key" UNIQUE ("team_name");



CREATE INDEX "idx_competitions_season" ON "public"."competitions" USING "btree" ("season");



CREATE INDEX "idx_match_entries_competition" ON "public"."match_team_entries" USING "btree" ("competition_id");



CREATE INDEX "idx_match_entries_match" ON "public"."match_team_entries" USING "btree" ("match_id");



CREATE INDEX "idx_match_entries_team" ON "public"."match_team_entries" USING "btree" ("team_id");



CREATE INDEX "idx_matches_season_date" ON "public"."matches" USING "btree" ("season", "match_date" DESC);



CREATE INDEX "idx_performances_player" ON "public"."player_match_performances" USING "btree" ("player_id");



CREATE INDEX "idx_performances_source_match" ON "public"."player_match_performances" USING "btree" ("source_match_id");



CREATE INDEX "idx_performances_team" ON "public"."player_match_performances" USING "btree" ("team_id");



ALTER TABLE ONLY "public"."competitions"
    ADD CONSTRAINT "competitions_season_fkey" FOREIGN KEY ("season") REFERENCES "public"."seasons"("season") ON UPDATE CASCADE ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."league_standings"
    ADD CONSTRAINT "league_standings_competition_id_fkey" FOREIGN KEY ("competition_id") REFERENCES "public"."competitions"("competition_id");



ALTER TABLE ONLY "public"."match_stories"
    ADD CONSTRAINT "match_stories_match_id_fkey" FOREIGN KEY ("match_id") REFERENCES "public"."matches"("match_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."match_stories"
    ADD CONSTRAINT "match_stories_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "public"."teams"("team_id") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."match_team_entries"
    ADD CONSTRAINT "match_team_entries_competition_id_fkey" FOREIGN KEY ("competition_id") REFERENCES "public"."competitions"("competition_id") ON UPDATE CASCADE ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."match_team_entries"
    ADD CONSTRAINT "match_team_entries_match_id_fkey" FOREIGN KEY ("match_id") REFERENCES "public"."matches"("match_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."match_team_entries"
    ADD CONSTRAINT "match_team_entries_opponent_id_fkey" FOREIGN KEY ("opponent_id") REFERENCES "public"."opponents"("opponent_id") ON UPDATE CASCADE ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."match_team_entries"
    ADD CONSTRAINT "match_team_entries_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "public"."teams"("team_id") ON UPDATE CASCADE ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."matches"
    ADD CONSTRAINT "matches_season_fkey" FOREIGN KEY ("season") REFERENCES "public"."seasons"("season") ON UPDATE CASCADE ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."player_match_performances"
    ADD CONSTRAINT "player_match_performances_player_id_fkey" FOREIGN KEY ("player_id") REFERENCES "public"."players"("player_id") ON UPDATE CASCADE ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."player_match_performances"
    ADD CONSTRAINT "player_match_performances_source_match_id_fkey" FOREIGN KEY ("source_match_id") REFERENCES "public"."match_team_entries"("source_match_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."player_match_performances"
    ADD CONSTRAINT "player_match_performances_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "public"."teams"("team_id") ON UPDATE CASCADE ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."player_profiles"
    ADD CONSTRAINT "player_profiles_player_id_fkey" FOREIGN KEY ("player_id") REFERENCES "public"."players"("player_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."team_profiles"
    ADD CONSTRAINT "team_profiles_season_fkey" FOREIGN KEY ("season") REFERENCES "public"."seasons"("season") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."team_profiles"
    ADD CONSTRAINT "team_profiles_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "public"."teams"("team_id") ON UPDATE CASCADE ON DELETE CASCADE;



CREATE POLICY "Allow public read access to league standings" ON "public"."league_standings" FOR SELECT TO "authenticated", "anon" USING (true);



CREATE POLICY "Public read competitions" ON "public"."competitions" FOR SELECT TO "authenticated", "anon" USING (true);



CREATE POLICY "Public read match stories" ON "public"."match_stories" FOR SELECT TO "authenticated", "anon" USING (true);



CREATE POLICY "Public read match team entries" ON "public"."match_team_entries" FOR SELECT TO "authenticated", "anon" USING (true);



CREATE POLICY "Public read matches" ON "public"."matches" FOR SELECT TO "authenticated", "anon" USING (true);



CREATE POLICY "Public read opponents" ON "public"."opponents" FOR SELECT TO "authenticated", "anon" USING (true);



CREATE POLICY "Public read player performances" ON "public"."player_match_performances" FOR SELECT TO "authenticated", "anon" USING (true);



CREATE POLICY "Public read player profiles" ON "public"."player_profiles" FOR SELECT TO "authenticated", "anon" USING (true);



CREATE POLICY "Public read players" ON "public"."players" FOR SELECT TO "authenticated", "anon" USING (true);



CREATE POLICY "Public read seasons" ON "public"."seasons" FOR SELECT TO "authenticated", "anon" USING (true);



CREATE POLICY "Public read team profiles" ON "public"."team_profiles" FOR SELECT TO "authenticated", "anon" USING (true);



CREATE POLICY "Public read teams" ON "public"."teams" FOR SELECT TO "authenticated", "anon" USING (true);



ALTER TABLE "public"."competitions" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."league_standings" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."match_stories" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."match_team_entries" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."matches" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."opponents" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."player_match_performances" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."player_profiles" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."players" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."seasons" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."team_profiles" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."teams" ENABLE ROW LEVEL SECURITY;


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



GRANT SELECT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."competitions" TO "anon";
GRANT SELECT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."competitions" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."competitions" TO "service_role";



GRANT SELECT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."league_standings" TO "anon";
GRANT SELECT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."league_standings" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."league_standings" TO "service_role";



GRANT SELECT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."match_stories" TO "anon";
GRANT SELECT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."match_stories" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."match_stories" TO "service_role";



GRANT SELECT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."match_team_entries" TO "anon";
GRANT SELECT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."match_team_entries" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."match_team_entries" TO "service_role";



GRANT SELECT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."matches" TO "anon";
GRANT SELECT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."matches" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."matches" TO "service_role";



GRANT SELECT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."opponents" TO "anon";
GRANT SELECT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."opponents" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."opponents" TO "service_role";



GRANT SELECT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."player_match_performances" TO "anon";
GRANT SELECT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."player_match_performances" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."player_match_performances" TO "service_role";



GRANT SELECT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."player_profiles" TO "anon";
GRANT SELECT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."player_profiles" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."player_profiles" TO "service_role";



GRANT SELECT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."players" TO "anon";
GRANT SELECT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."players" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."players" TO "service_role";



GRANT SELECT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."seasons" TO "anon";
GRANT SELECT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."seasons" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."seasons" TO "service_role";



GRANT SELECT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."team_profiles" TO "anon";
GRANT SELECT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."team_profiles" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."team_profiles" TO "service_role";



GRANT SELECT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."teams" TO "anon";
GRANT SELECT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."teams" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."teams" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLES TO "service_role";







