-- =========================================================
-- DCC player profile claims
--
-- A DCC App account may exist without a linked cricket
-- player identity. A claim is only a request to establish
-- that link and grants no player identity by itself.
-- =========================================================

create table public.player_profile_claims (
    claim_id bigint generated by default as identity primary key,

    user_id uuid not null
        references public.user_profiles(user_id)
        on update cascade
        on delete cascade,

    player_id text not null
        references public.players(player_id)
        on update cascade
        on delete restrict,

    status text not null default 'Pending',

    requested_at timestamptz not null default now(),

    reviewed_by uuid
        references public.user_profiles(user_id)
        on update cascade
        on delete restrict,

    reviewed_at timestamptz,

    review_note text,

    constraint player_profile_claims_status_check
        check (
            status in (
                'Pending',
                'Approved',
                'Rejected',
                'Cancelled'
            )
        ),

    constraint player_profile_claims_review_state_check
        check (
            (
                status = 'Pending'
                and reviewed_by is null
                and reviewed_at is null
            )
            or
            (
                status = 'Cancelled'
                and reviewed_by is null
                and reviewed_at is null
            )
            or
            (
                status in ('Approved', 'Rejected')
                and reviewed_by is not null
                and reviewed_at is not null
            )
        )
);

-- A user may have only one unresolved player-profile claim.
create unique index player_profile_claims_one_pending_per_user
    on public.player_profile_claims(user_id)
    where status = 'Pending';

alter table public.player_profile_claims
enable row level security;

-- =========================================================
-- Row Level Security
-- =========================================================

-- An authenticated user may view only their own claims.
create policy "Users can view their own player profile claims"
on public.player_profile_claims
for select
to authenticated
using (
    user_id = auth.uid()
);

-- Active Super Admins may view every claim for review.
create policy "Super Admins can view all player profile claims"
on public.player_profile_claims
for select
to authenticated
using (
    public.is_active_super_admin()
);

grant select
on public.player_profile_claims
to authenticated;

-- =========================================================
-- Super Admin player-profile claim decision
--
-- A claim itself never grants player identity. Only this
-- controlled Super Admin operation may approve a claim and
-- establish the account-to-player link.
-- =========================================================

create or replace function public.review_player_profile_claim(
    target_claim_id bigint,
    decision text,
    decision_note text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
    claim_record public.player_profile_claims%rowtype;
    target_account public.user_profiles%rowtype;
begin
    -- Only an Active Super Admin may review player claims.
    if not public.is_active_super_admin() then
        raise exception 'Only an active Super Admin may review player profile claims.';
    end if;

    -- Keep the public decision surface deliberately narrow.
    if decision not in ('Approved', 'Rejected') then
        raise exception 'Decision must be Approved or Rejected.';
    end if;

    -- Lock the claim so two review attempts cannot process
    -- the same Pending claim concurrently.
    select *
    into claim_record
    from public.player_profile_claims
    where claim_id = target_claim_id
    for update;

    if not found then
        raise exception 'Player profile claim % does not exist.', target_claim_id;
    end if;

    if claim_record.status <> 'Pending' then
        raise exception
            'Player profile claim % is no longer Pending.',
            target_claim_id;
    end if;

    -- Lock the claimant's account before checking eligibility.
    select *
    into target_account
    from public.user_profiles
    where user_id = claim_record.user_id
    for update;

    if not found then
        raise exception 'The claimant account no longer exists.';
    end if;

    if decision = 'Approved' then
        if target_account.status <> 'Active' then
            raise exception
                'Only an Active DCC account may be linked to a player profile.';
        end if;

        if target_account.player_id is not null then
            raise exception
                'This DCC account is already linked to a player profile.';
        end if;

        -- Lock the canonical player row. Competing approval attempts
        -- for the same permanent player identity will serialise here.
        perform 1
        from public.players
        where player_id = claim_record.player_id
        for update;

        if not found then
            raise exception
                'The claimed player profile no longer exists.';
        end if;

        -- Re-check ownership after obtaining the player-specific lock.
        if exists (
            select 1
            from public.user_profiles up
            where up.player_id = claim_record.player_id
              and up.status = 'Active'
        ) then
            raise exception
                'This player profile is already linked to an Active DCC account.';
        end if;

        -- Establish the permanent player link.
        update public.user_profiles
        set
            player_id = claim_record.player_id,
            updated_at = now()
        where user_id = claim_record.user_id;

        -- Record the approved claim.
        update public.player_profile_claims
        set
            status = 'Approved',
            reviewed_by = auth.uid(),
            reviewed_at = now(),
            review_note = decision_note
        where claim_id = target_claim_id;

        -- Any other unresolved claims for this same player can no
        -- longer succeed. Preserve them as rejected audit records.
        update public.player_profile_claims
        set
            status = 'Rejected',
            reviewed_by = auth.uid(),
            reviewed_at = now(),
            review_note = coalesce(
                review_note,
                'Automatically rejected because another claim for this player profile was approved.'
            )
        where player_id = claim_record.player_id
          and status = 'Pending'
          and claim_id <> target_claim_id;

    else
        -- Rejection changes only the claim. The general DCC account
        -- remains Active and unlinked.
        update public.player_profile_claims
        set
            status = 'Rejected',
            reviewed_by = auth.uid(),
            reviewed_at = now(),
            review_note = decision_note
        where claim_id = target_claim_id;
    end if;
end;
$$;

revoke all
on function public.review_player_profile_claim(bigint, text, text)
from public;

grant execute
on function public.review_player_profile_claim(bigint, text, text)
to authenticated;

-- =========================================================
-- Player-profile claim creation
--
-- An Active, currently unlinked DCC account may submit one
-- Pending claim. Creating a claim does not grant player
-- identity or player-specific access.
-- =========================================================

create or replace function public.create_player_profile_claim(
    target_player_id text
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
    caller_account public.user_profiles%rowtype;
    new_claim_id bigint;
begin
    if auth.uid() is null then
        raise exception 'Authentication is required.';
    end if;

    -- Lock the caller's account so its eligibility cannot change
    -- concurrently while the claim is being created.
    select *
    into caller_account
    from public.user_profiles
    where user_id = auth.uid()
    for update;

    if not found then
        raise exception 'Your DCC account profile does not exist.';
    end if;

    if caller_account.status <> 'Active' then
        raise exception 'Only an Active DCC account may claim a player profile.';
    end if;

    if caller_account.player_id is not null then
        raise exception 'Your DCC account is already linked to a player profile.';
    end if;

    if target_player_id is null
       or pg_catalog.btrim(target_player_id) = '' then
        raise exception 'A player profile must be selected.';
    end if;

    if not exists (
        select 1
        from public.players p
        where p.player_id = target_player_id
    ) then
        raise exception 'The selected player profile does not exist.';
    end if;

    if exists (
        select 1
        from public.user_profiles up
        where up.player_id = target_player_id
          and up.status = 'Active'
    ) then
        raise exception 'This player profile is already linked to an Active DCC account.';
    end if;

    if exists (
        select 1
        from public.player_profile_claims ppc
        where ppc.user_id = auth.uid()
          and ppc.status = 'Pending'
    ) then
        raise exception 'You already have a Pending player-profile claim.';
    end if;

    insert into public.player_profile_claims (
        user_id,
        player_id
    )
    values (
        auth.uid(),
        target_player_id
    )
    returning claim_id into new_claim_id;

    return new_claim_id;
end;
$$;

revoke all
on function public.create_player_profile_claim(text)
from public;

grant execute
on function public.create_player_profile_claim(text)
to authenticated;
