-- DCC Portal / App
-- Match availability foundation
--
-- Availability is deliberately separate from the existence of a fixture.
--
-- Lifecycle:
--   Fixture exists
--       -> availability Not Open (no poll row)
--       -> Team Admin / Match Admin opens poll
--       -> audience snapshot is created
--       -> players respond Available / Unavailable
--       -> administrator may close the poll
--
-- "Not Responded" is derived:
--   player is in the poll audience
--   AND no response row exists for that player.
--
-- Future fixtures do NOT automatically become availability polls.


-- ============================================================
-- 1. Availability polls
-- ============================================================

create table public.match_availability_polls (
  poll_id bigint generated by default as identity primary key,

  match_id text not null
    references public.matches(match_id)
    on delete cascade,

  team_id text
    references public.teams(team_id)
    on delete cascade,

  status text not null default 'Open',

  opened_at timestamptz not null default now(),

  opened_by uuid not null
    references auth.users(id),

  closed_at timestamptz,

  closed_by uuid
    references auth.users(id),

  created_at timestamptz not null default now(),

  updated_at timestamptz not null default now(),

  constraint match_availability_polls_status_check
    check (status in ('Open', 'Closed')),

  constraint match_availability_polls_close_state_check
    check (
      (
        status = 'Open'
        and closed_at is null
        and closed_by is null
      )
      or
      (
        status = 'Closed'
        and closed_at is not null
        and closed_by is not null
      )
    )
);


-- A normal team fixture may have only one availability poll
-- for that match/team combination.

create unique index match_availability_polls_match_team_unique
  on public.match_availability_polls (
    match_id,
    team_id
  )
  where team_id is not null;


-- An ad-hoc match without a canonical team scope may have
-- only one match-level availability poll.

create unique index match_availability_polls_match_only_unique
  on public.match_availability_polls (match_id)
  where team_id is null;


create index match_availability_polls_match_idx
  on public.match_availability_polls (match_id);


create index match_availability_polls_team_status_idx
  on public.match_availability_polls (
    team_id,
    status
  )
  where team_id is not null;


-- ============================================================
-- 2. Availability audience snapshot
-- ============================================================
--
-- This table records who was actually asked for availability.
--
-- It is intentionally a snapshot.
--
-- If somebody later joins/leaves a team, that must not rewrite
-- the historical audience of an already-opened poll.
-- ============================================================

create table public.match_availability_audience (
  audience_id bigint generated by default as identity primary key,

  poll_id bigint not null
    references public.match_availability_polls(poll_id)
    on delete cascade,

  player_id text not null
    references public.players(player_id),

  added_at timestamptz not null default now(),

  added_by uuid not null
    references auth.users(id),

  created_at timestamptz not null default now(),

  constraint match_availability_audience_poll_player_unique
    unique (poll_id, player_id)
);


create index match_availability_audience_player_idx
  on public.match_availability_audience (player_id);


create index match_availability_audience_poll_idx
  on public.match_availability_audience (poll_id);


-- ============================================================
-- 3. Player responses
-- ============================================================
--
-- Only explicit player choices are stored.
--
-- Stored:
--   Available
--   Unavailable
--
-- NOT stored:
--   Not Responded
--
-- Not Responded = audience member with no response row.
-- ============================================================

create table public.match_availability (
  availability_id bigint generated by default as identity primary key,

  poll_id bigint not null
    references public.match_availability_polls(poll_id)
    on delete cascade,

  player_id text not null
    references public.players(player_id),

  availability_status text not null,

  responded_at timestamptz not null default now(),

  updated_at timestamptz not null default now(),

  constraint match_availability_status_check
    check (
      availability_status in (
        'Available',
        'Unavailable'
      )
    ),

  constraint match_availability_poll_player_unique
    unique (poll_id, player_id)
);


create index match_availability_player_idx
  on public.match_availability (player_id);


create index match_availability_poll_status_idx
  on public.match_availability (
    poll_id,
    availability_status
  );


-- ============================================================
-- 4. RLS
-- ============================================================

alter table public.match_availability_polls
  enable row level security;

alter table public.match_availability_audience
  enable row level security;

alter table public.match_availability
  enable row level security;


-- ============================================================
-- 5. Read policies
-- ============================================================
--
-- Active authenticated DCC accounts may read availability data.
--
-- Write access is NOT granted directly.
-- All writes go through controlled RPC functions below.
-- ============================================================

create policy "Active DCC users can read availability polls"
on public.match_availability_polls
for select
to authenticated
using (
  exists (
    select 1
    from public.user_profiles up
    where up.user_id = auth.uid()
      and up.status = 'Active'
  )
);


create policy "Active DCC users can read availability audience"
on public.match_availability_audience
for select
to authenticated
using (
  exists (
    select 1
    from public.user_profiles up
    where up.user_id = auth.uid()
      and up.status = 'Active'
  )
);


create policy "Active DCC users can read availability responses"
on public.match_availability
for select
to authenticated
using (
  exists (
    select 1
    from public.user_profiles up
    where up.user_id = auth.uid()
      and up.status = 'Active'
  )
);


-- ============================================================
-- 6. Direct table privileges
-- ============================================================

revoke all
on table public.match_availability_polls
from public, anon, authenticated;

revoke all
on table public.match_availability_audience
from public, anon, authenticated;

revoke all
on table public.match_availability
from public, anon, authenticated;


grant select
on table public.match_availability_polls
to authenticated;

grant select
on table public.match_availability_audience
to authenticated;

grant select
on table public.match_availability
to authenticated;


-- ============================================================
-- 7. Availability-management authority
-- ============================================================
--
-- A user may administer availability when:
--
--   * they are an active Super Admin; OR
--   * they are an active match-specific admin; OR
--   * for a team-scoped poll, they are an active Team Admin
--     for that team.
--
-- This deliberately does NOT grant authority merely because
-- somebody is a player or availability audience member.
-- ============================================================

create or replace function public.can_manage_match_availability(
  target_match_id text,
  target_team_id text default null
)
returns boolean
language plpgsql
security definer
stable
set search_path = ''
as $$
declare
  current_user_id uuid;
  account_is_active boolean := false;
  account_is_super_admin boolean := false;
  is_match_admin boolean := false;
  is_team_admin boolean := false;
begin
  current_user_id := auth.uid();

  if current_user_id is null then
    return false;
  end if;


  select
    true,
    (up.account_role = 'Super Admin')
  into
    account_is_active,
    account_is_super_admin
  from public.user_profiles up
  where up.user_id = current_user_id
    and up.status = 'Active'
  limit 1;


  if not coalesce(account_is_active, false) then
    return false;
  end if;


  if coalesce(account_is_super_admin, false) then
    return true;
  end if;


  select exists (
    select 1
    from public.match_admin_assignments maa
    where maa.match_id = target_match_id
      and maa.user_id = current_user_id
      and maa.active = true
  )
  into is_match_admin;


  if is_match_admin then
    return true;
  end if;


  if target_team_id is not null then

    select exists (
      select 1
      from public.team_admin_assignments taa
      where taa.team_id = target_team_id
        and taa.user_id = current_user_id
        and taa.active = true
    )
    into is_team_admin;


    if is_team_admin then
      return true;
    end if;

  end if;


  return false;
end;
$$;


-- ============================================================
-- 8. Open a team availability poll
-- ============================================================
--
-- For a normal team fixture:
--
--   * Team Admin opens the poll manually.
--   * The team's CURRENT active membership is copied into the
--     availability audience as a snapshot.
--   * Later membership changes do not alter this poll.
--
-- The match must actually be associated with the requested
-- DCC team through match_team_entries.
-- ============================================================

create or replace function public.open_team_match_availability(
  target_match_id text,
  target_team_id text
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid;
  new_poll_id bigint;
  target_match_status text;
  team_is_on_match boolean := false;
  active_player_count integer := 0;
begin
  current_user_id := auth.uid();


  if current_user_id is null then
    raise exception 'Authentication required.';
  end if;


  if target_match_id is null
     or btrim(target_match_id) = '' then
    raise exception 'Match ID is required.';
  end if;


  if target_team_id is null
     or btrim(target_team_id) = '' then
    raise exception 'Team ID is required.';
  end if;


  if not public.can_manage_match_availability(
    target_match_id,
    target_team_id
  ) then
    raise exception
      'You do not have permission to manage availability for this match.';
  end if;


  select m.status
  into target_match_status
  from public.matches m
  where m.match_id = target_match_id
  for update;


  if not found then
    raise exception 'Match not found.';
  end if;


  if target_match_status <> 'Scheduled' then
    raise exception
      'Availability can only be opened for a scheduled match.';
  end if;


  select exists (
    select 1
    from public.match_team_entries mte
    where mte.match_id = target_match_id
      and mte.team_id = target_team_id
  )
  into team_is_on_match;


  if not team_is_on_match then
    raise exception
      'The selected DCC team is not linked to this match.';
  end if;


  if exists (
    select 1
    from public.match_availability_polls map
    where map.match_id = target_match_id
      and map.team_id = target_team_id
  ) then
    raise exception
      'An availability poll already exists for this match and team.';
  end if;


  select count(*)
  into active_player_count
  from public.team_player_memberships tpm
  join public.players p
    on p.player_id = tpm.player_id
  where tpm.team_id = target_team_id
    and tpm.active = true
    and p.active = true;


  if active_player_count = 0 then
    raise exception
      'This team has no active players available for the poll audience.';
  end if;


  insert into public.match_availability_polls (
    match_id,
    team_id,
    status,
    opened_at,
    opened_by,
    updated_at
  )
  values (
    target_match_id,
    target_team_id,
    'Open',
    now(),
    current_user_id,
    now()
  )
  returning poll_id
  into new_poll_id;


  insert into public.match_availability_audience (
    poll_id,
    player_id,
    added_at,
    added_by
  )
  select
    new_poll_id,
    tpm.player_id,
    now(),
    current_user_id
  from public.team_player_memberships tpm
  join public.players p
    on p.player_id = tpm.player_id
  where tpm.team_id = target_team_id
    and tpm.active = true
    and p.active = true;


  return new_poll_id;
end;
$$;


-- ============================================================
-- 9. Open an ad-hoc/custom availability poll
-- ============================================================
--
-- Some Friendly / Warm-up / Internal matches may not belong
-- naturally to one normal DCC team.
--
-- A match-specific administrator may therefore open a
-- match-level poll and then deliberately build its audience.
--
-- This does NOT apply to Official Season matches.
-- ============================================================

create or replace function public.open_custom_match_availability(
  target_match_id text
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid;
  new_poll_id bigint;
  target_match_status text;
  target_stats_category text;
begin
  current_user_id := auth.uid();


  if current_user_id is null then
    raise exception 'Authentication required.';
  end if;


  if target_match_id is null
     or btrim(target_match_id) = '' then
    raise exception 'Match ID is required.';
  end if;


  if not public.can_manage_match_availability(
    target_match_id,
    null
  ) then
    raise exception
      'You do not have permission to manage availability for this match.';
  end if;


  select
    m.status,
    m.stats_category
  into
    target_match_status,
    target_stats_category
  from public.matches m
  where m.match_id = target_match_id
  for update;


  if not found then
    raise exception 'Match not found.';
  end if;


  if target_match_status <> 'Scheduled' then
    raise exception
      'Availability can only be opened for a scheduled match.';
  end if;


  if target_stats_category not in (
    'Friendly',
    'Warm-up',
    'Internal'
  ) then
    raise exception
      'Custom availability polls are only available for Friendly, Warm-up or Internal matches.';
  end if;


  if exists (
    select 1
    from public.match_availability_polls map
    where map.match_id = target_match_id
      and map.team_id is null
  ) then
    raise exception
      'A custom availability poll already exists for this match.';
  end if;


  insert into public.match_availability_polls (
    match_id,
    team_id,
    status,
    opened_at,
    opened_by,
    updated_at
  )
  values (
    target_match_id,
    null,
    'Open',
    now(),
    current_user_id,
    now()
  )
  returning poll_id
  into new_poll_id;


  return new_poll_id;
end;
$$;


-- ============================================================
-- 10. Add a player to an availability audience
-- ============================================================
--
-- Used for:
--   * ad-hoc/custom match audiences;
--   * legitimate additions after a normal poll has opened.
--
-- This does NOT alter permanent team membership.
-- ============================================================

create or replace function public.add_player_to_availability_audience(
  target_poll_id bigint,
  target_player_id text
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid;
  target_match_id text;
  target_team_id text;
  target_poll_status text;
  target_player_active boolean := false;
  new_audience_id bigint;
begin
  current_user_id := auth.uid();


  if current_user_id is null then
    raise exception 'Authentication required.';
  end if;


  if target_poll_id is null then
    raise exception 'Poll ID is required.';
  end if;


  if target_player_id is null
     or btrim(target_player_id) = '' then
    raise exception 'Player ID is required.';
  end if;


  select
    map.match_id,
    map.team_id,
    map.status
  into
    target_match_id,
    target_team_id,
    target_poll_status
  from public.match_availability_polls map
  where map.poll_id = target_poll_id
  for update;


  if not found then
    raise exception 'Availability poll not found.';
  end if;


  if target_poll_status <> 'Open' then
    raise exception
      'Players can only be added while the availability poll is open.';
  end if;


  if not public.can_manage_match_availability(
    target_match_id,
    target_team_id
  ) then
    raise exception
      'You do not have permission to manage this availability poll.';
  end if;


  select p.active
  into target_player_active
  from public.players p
  where p.player_id = target_player_id;


  if not found then
    raise exception 'Player not found.';
  end if;


  if not coalesce(target_player_active, false) then
    raise exception
      'Only active DCC players can be added to an availability poll.';
  end if;


  if exists (
    select 1
    from public.match_availability_audience maa
    where maa.poll_id = target_poll_id
      and maa.player_id = target_player_id
  ) then
    raise exception
      'This player is already in the availability audience.';
  end if;


  insert into public.match_availability_audience (
    poll_id,
    player_id,
    added_at,
    added_by
  )
  values (
    target_poll_id,
    target_player_id,
    now(),
    current_user_id
  )
  returning audience_id
  into new_audience_id;


  return new_audience_id;
end;
$$;


-- ============================================================
-- 11. Remove a player from an availability audience
-- ============================================================
--
-- Removing somebody from the audience also removes any response
-- they supplied for that poll.
--
-- This is an administrative correction to the poll audience,
-- NOT a change to permanent team membership.
-- ============================================================

create or replace function public.remove_player_from_availability_audience(
  target_poll_id bigint,
  target_player_id text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid;
  target_match_id text;
  target_team_id text;
  target_poll_status text;
begin
  current_user_id := auth.uid();


  if current_user_id is null then
    raise exception 'Authentication required.';
  end if;


  if target_poll_id is null then
    raise exception 'Poll ID is required.';
  end if;


  if target_player_id is null
     or btrim(target_player_id) = '' then
    raise exception 'Player ID is required.';
  end if;


  select
    map.match_id,
    map.team_id,
    map.status
  into
    target_match_id,
    target_team_id,
    target_poll_status
  from public.match_availability_polls map
  where map.poll_id = target_poll_id
  for update;


  if not found then
    raise exception 'Availability poll not found.';
  end if;


  if target_poll_status <> 'Open' then
    raise exception
      'The availability audience can only be changed while the poll is open.';
  end if;


  if not public.can_manage_match_availability(
    target_match_id,
    target_team_id
  ) then
    raise exception
      'You do not have permission to manage this availability poll.';
  end if;


  if not exists (
    select 1
    from public.match_availability_audience maa
    where maa.poll_id = target_poll_id
      and maa.player_id = target_player_id
  ) then
    raise exception
      'This player is not in the availability audience.';
  end if;


  delete from public.match_availability
  where poll_id = target_poll_id
    and player_id = target_player_id;


  delete from public.match_availability_audience
  where poll_id = target_poll_id
    and player_id = target_player_id;
end;
$$;


-- ============================================================
-- 12. Submit / change MY availability
-- ============================================================
--
-- Important security rule:
--
-- The client does NOT supply a player_id.
--
-- We derive the player from:
--
--   auth.uid()
--       -> user_profiles
--       -> player_id
--
-- Therefore a player cannot use this RPC to submit availability
-- on behalf of somebody else.
--
-- Re-submitting changes the same response row.
-- ============================================================

create or replace function public.set_my_match_availability(
  target_poll_id bigint,
  target_availability_status text
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid;
  current_player_id text;
  target_poll_status text;
  resulting_availability_id bigint;
begin
  current_user_id := auth.uid();


  if current_user_id is null then
    raise exception 'Authentication required.';
  end if;


  if target_poll_id is null then
    raise exception 'Poll ID is required.';
  end if;


  if target_availability_status not in (
    'Available',
    'Unavailable'
  ) then
    raise exception
      'Availability must be Available or Unavailable.';
  end if;


  select up.player_id
  into current_player_id
  from public.user_profiles up
  where up.user_id = current_user_id
    and up.status = 'Active'
  limit 1;


  if current_player_id is null then
    raise exception
      'Your active DCC account is not linked to a player.';
  end if;


  if not exists (
    select 1
    from public.players p
    where p.player_id = current_player_id
      and p.active = true
  ) then
    raise exception
      'Your linked DCC player is not active.';
  end if;


  select map.status
  into target_poll_status
  from public.match_availability_polls map
  where map.poll_id = target_poll_id
  for update;


  if not found then
    raise exception 'Availability poll not found.';
  end if;


  if target_poll_status <> 'Open' then
    raise exception
      'This availability poll is not open.';
  end if;


  if not exists (
    select 1
    from public.match_availability_audience maa
    where maa.poll_id = target_poll_id
      and maa.player_id = current_player_id
  ) then
    raise exception
      'You are not in the availability audience for this match.';
  end if;


  insert into public.match_availability (
    poll_id,
    player_id,
    availability_status,
    responded_at,
    updated_at
  )
  values (
    target_poll_id,
    current_player_id,
    target_availability_status,
    now(),
    now()
  )
  on conflict (poll_id, player_id)
  do update
  set
    availability_status = excluded.availability_status,
    responded_at = now(),
    updated_at = now()
  returning availability_id
  into resulting_availability_id;


  return resulting_availability_id;
end;
$$;


-- ============================================================
-- 13. Clear MY availability response
-- ============================================================
--
-- While the poll remains open, a player may clear their answer.
-- They then return to the derived "Not Responded" state.
-- ============================================================

create or replace function public.clear_my_match_availability(
  target_poll_id bigint
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid;
  current_player_id text;
  target_poll_status text;
begin
  current_user_id := auth.uid();


  if current_user_id is null then
    raise exception 'Authentication required.';
  end if;


  if target_poll_id is null then
    raise exception 'Poll ID is required.';
  end if;


  select up.player_id
  into current_player_id
  from public.user_profiles up
  where up.user_id = current_user_id
    and up.status = 'Active'
  limit 1;


  if current_player_id is null then
    raise exception
      'Your active DCC account is not linked to a player.';
  end if;


  select map.status
  into target_poll_status
  from public.match_availability_polls map
  where map.poll_id = target_poll_id
  for update;


  if not found then
    raise exception 'Availability poll not found.';
  end if;


  if target_poll_status <> 'Open' then
    raise exception
      'This availability poll is not open.';
  end if;


  if not exists (
    select 1
    from public.match_availability_audience maa
    where maa.poll_id = target_poll_id
      and maa.player_id = current_player_id
  ) then
    raise exception
      'You are not in the availability audience for this match.';
  end if;


  delete from public.match_availability
  where poll_id = target_poll_id
    and player_id = current_player_id;
end;
$$;


-- ============================================================
-- 14. Close availability poll
-- ============================================================

create or replace function public.close_match_availability(
  target_poll_id bigint
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid;
  target_match_id text;
  target_team_id text;
  target_poll_status text;
begin
  current_user_id := auth.uid();


  if current_user_id is null then
    raise exception 'Authentication required.';
  end if;


  if target_poll_id is null then
    raise exception 'Poll ID is required.';
  end if;


  select
    map.match_id,
    map.team_id,
    map.status
  into
    target_match_id,
    target_team_id,
    target_poll_status
  from public.match_availability_polls map
  where map.poll_id = target_poll_id
  for update;


  if not found then
    raise exception 'Availability poll not found.';
  end if;


  if not public.can_manage_match_availability(
    target_match_id,
    target_team_id
  ) then
    raise exception
      'You do not have permission to manage this availability poll.';
  end if;


  if target_poll_status = 'Closed' then
    raise exception
      'This availability poll is already closed.';
  end if;


  update public.match_availability_polls
  set
    status = 'Closed',
    closed_at = now(),
    closed_by = current_user_id,
    updated_at = now()
  where poll_id = target_poll_id;
end;
$$;


-- ============================================================
-- 15. Re-open availability poll
-- ============================================================
--
-- Real cricket changes.
--
-- A Team Admin may need to re-open a poll after somebody drops
-- out, a match is rearranged, etc.
--
-- Existing audience and responses are preserved.
-- ============================================================

create or replace function public.reopen_match_availability(
  target_poll_id bigint
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid;
  target_match_id text;
  target_team_id text;
  target_poll_status text;
  target_match_status text;
begin
  current_user_id := auth.uid();


  if current_user_id is null then
    raise exception 'Authentication required.';
  end if;


  if target_poll_id is null then
    raise exception 'Poll ID is required.';
  end if;


  select
    map.match_id,
    map.team_id,
    map.status
  into
    target_match_id,
    target_team_id,
    target_poll_status
  from public.match_availability_polls map
  where map.poll_id = target_poll_id
  for update;


  if not found then
    raise exception 'Availability poll not found.';
  end if;


  if not public.can_manage_match_availability(
    target_match_id,
    target_team_id
  ) then
    raise exception
      'You do not have permission to manage this availability poll.';
  end if;


  if target_poll_status = 'Open' then
    raise exception
      'This availability poll is already open.';
  end if;


  select m.status
  into target_match_status
  from public.matches m
  where m.match_id = target_match_id;


  if not found then
    raise exception 'Match not found.';
  end if;


  if target_match_status <> 'Scheduled' then
    raise exception
      'Availability can only be re-opened while the match is scheduled.';
  end if;


  update public.match_availability_polls
  set
    status = 'Open',
    closed_at = null,
    closed_by = null,
    updated_at = now()
  where poll_id = target_poll_id;
end;
$$;


-- ============================================================
-- 16. Function privileges
-- ============================================================

revoke all
on function public.can_manage_match_availability(text, text)
from public;

revoke all
on function public.open_team_match_availability(text, text)
from public;

revoke all
on function public.open_custom_match_availability(text)
from public;

revoke all
on function public.add_player_to_availability_audience(bigint, text)
from public;

revoke all
on function public.remove_player_from_availability_audience(bigint, text)
from public;

revoke all
on function public.set_my_match_availability(bigint, text)
from public;

revoke all
on function public.clear_my_match_availability(bigint)
from public;

revoke all
on function public.close_match_availability(bigint)
from public;

revoke all
on function public.reopen_match_availability(bigint)
from public;


grant execute
on function public.can_manage_match_availability(text, text)
to authenticated;

grant execute
on function public.open_team_match_availability(text, text)
to authenticated;

grant execute
on function public.open_custom_match_availability(text)
to authenticated;

grant execute
on function public.add_player_to_availability_audience(bigint, text)
to authenticated;

grant execute
on function public.remove_player_from_availability_audience(bigint, text)
to authenticated;

grant execute
on function public.set_my_match_availability(bigint, text)
to authenticated;

grant execute
on function public.clear_my_match_availability(bigint)
to authenticated;

grant execute
on function public.close_match_availability(bigint)
to authenticated;

grant execute
on function public.reopen_match_availability(bigint)
to authenticated;