-- DCC Portal / App
-- Match team-selection foundation
--
-- Core principle:
--   Availability informs selection but never controls it.
--
-- A Team Admin / Match Admin may create and publish a selection
-- whether:
--   * no availability poll exists;
--   * availability is Open;
--   * availability is Closed;
--   * a selected player responded Available;
--   * a selected player responded Unavailable; or
--   * a selected player did not respond.
--
-- Selection is therefore an independent match workflow.


-- ============================================================
-- 1. Match selections
-- ============================================================

create table public.match_selections (
  selection_id bigint generated by default as identity primary key,

  match_id text not null
    references public.matches(match_id)
    on delete cascade,

  team_id text not null
    references public.teams(team_id),

  status text not null default 'Draft',

  created_by uuid not null
    references auth.users(id),

  created_at timestamptz not null default now(),

  updated_by uuid not null
    references auth.users(id),

  updated_at timestamptz not null default now(),

  published_by uuid
    references auth.users(id),

  published_at timestamptz,

  constraint match_selections_status_check
    check (status in ('Draft', 'Published')),

  constraint match_selections_publish_state_check
    check (
      (
        status = 'Draft'
        and published_by is null
        and published_at is null
      )
      or
      (
        status = 'Published'
        and published_by is not null
        and published_at is not null
      )
    ),

  constraint match_selections_match_team_unique
    unique (match_id, team_id)
);


create index match_selections_team_status_idx
  on public.match_selections (
    team_id,
    status
  );


create index match_selections_match_idx
  on public.match_selections (match_id);


-- ============================================================
-- 2. Selected players
-- ============================================================
--
-- No foreign-key relationship to team_player_memberships exists
-- deliberately.
--
-- A player does NOT need to be a normal member of this team to
-- be selected for this particular match.
--
-- Likewise, no availability response is required.
-- ============================================================

create table public.match_selection_players (
  selection_player_id bigint generated by default as identity primary key,

  selection_id bigint not null
    references public.match_selections(selection_id)
    on delete cascade,

  player_id text not null
    references public.players(player_id),

  batting_position integer,

  is_captain boolean not null default false,

  is_wicketkeeper boolean not null default false,

  added_at timestamptz not null default now(),

  added_by uuid not null
    references auth.users(id),

  updated_at timestamptz not null default now(),

  updated_by uuid not null
    references auth.users(id),

  constraint match_selection_players_unique
    unique (selection_id, player_id),

  constraint match_selection_players_batting_position_check
    check (
      batting_position is null
      or batting_position >= 1
    )
);


create unique index match_selection_one_batting_position
  on public.match_selection_players (
    selection_id,
    batting_position
  )
  where batting_position is not null;


create unique index match_selection_one_captain
  on public.match_selection_players (selection_id)
  where is_captain = true;


create unique index match_selection_one_wicketkeeper
  on public.match_selection_players (selection_id)
  where is_wicketkeeper = true;


create index match_selection_players_player_idx
  on public.match_selection_players (player_id);


-- ============================================================
-- 3. RLS
-- ============================================================

alter table public.match_selections
  enable row level security;

alter table public.match_selection_players
  enable row level security;


-- ============================================================
-- 4. Read policies
-- ============================================================

create policy "Active DCC users can read match selections"
on public.match_selections
for select
to authenticated
using (
  exists (
    select 1
    from public.user_profiles up
    where up.user_id = auth.uid()
      and up.status = 'Active'
  )
);


create policy "Active DCC users can read selected players"
on public.match_selection_players
for select
to authenticated
using (
  exists (
    select 1
    from public.user_profiles up
    where up.user_id = auth.uid()
      and up.status = 'Active'
  )
);


-- ============================================================
-- 5. Direct table privileges
-- ============================================================
--
-- Clients may read selections but may not write directly.
-- All writes go through the controlled RPC functions below.
-- ============================================================

revoke all
on table public.match_selections
from public, anon, authenticated;

revoke all
on table public.match_selection_players
from public, anon, authenticated;


grant select
on table public.match_selections
to authenticated;

grant select
on table public.match_selection_players
to authenticated;


-- ============================================================
-- 6. Selection-management authority
-- ============================================================
--
-- Authority:
--
--   * active Super Admin; OR
--   * active match-specific admin; OR
--   * active Team Admin for the selected DCC team.
-- ============================================================

create or replace function public.can_manage_match_selection(
  target_match_id text,
  target_team_id text
)
returns boolean
language plpgsql
security definer
stable
set search_path = ''
as $$
declare
  current_user_id uuid;
  account_is_active boolean := false;
  account_is_super_admin boolean := false;
  is_match_admin boolean := false;
  is_team_admin boolean := false;
begin
  current_user_id := auth.uid();

  if current_user_id is null then
    return false;
  end if;


  select
    true,
    (up.account_role = 'Super Admin')
  into
    account_is_active,
    account_is_super_admin
  from public.user_profiles up
  where up.user_id = current_user_id
    and up.status = 'Active'
  limit 1;


  if not coalesce(account_is_active, false) then
    return false;
  end if;


  if coalesce(account_is_super_admin, false) then
    return true;
  end if;


  select exists (
    select 1
    from public.match_admin_assignments maa
    where maa.match_id = target_match_id
      and maa.user_id = current_user_id
      and maa.active = true
  )
  into is_match_admin;


  if is_match_admin then
    return true;
  end if;


  select exists (
    select 1
    from public.team_admin_assignments taa
    where taa.team_id = target_team_id
      and taa.user_id = current_user_id
      and taa.active = true
  )
  into is_team_admin;


  return is_team_admin;
end;
$$;


-- ============================================================
-- 7. Create / obtain draft selection
-- ============================================================

create or replace function public.create_match_selection(
  target_match_id text,
  target_team_id text
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid;
  target_match_status text;
  team_is_on_match boolean := false;
  existing_selection_id bigint;
  new_selection_id bigint;
begin
  current_user_id := auth.uid();


  if current_user_id is null then
    raise exception 'Authentication required.';
  end if;


  if target_match_id is null
     or btrim(target_match_id) = '' then
    raise exception 'Match ID is required.';
  end if;


  if target_team_id is null
     or btrim(target_team_id) = '' then
    raise exception 'Team ID is required.';
  end if;


  if not public.can_manage_match_selection(
    target_match_id,
    target_team_id
  ) then
    raise exception
      'You do not have permission to manage selection for this match.';
  end if;


  select m.status
  into target_match_status
  from public.matches m
  where m.match_id = target_match_id
  for update;


  if not found then
    raise exception 'Match not found.';
  end if;


  if target_match_status <> 'Scheduled' then
    raise exception
      'Team selection can only be created for a scheduled match.';
  end if;


  select exists (
    select 1
    from public.match_team_entries mte
    where mte.match_id = target_match_id
      and mte.team_id = target_team_id
  )
  into team_is_on_match;


  if not team_is_on_match then
    raise exception
      'The selected DCC team is not linked to this match.';
  end if;


  select ms.selection_id
  into existing_selection_id
  from public.match_selections ms
  where ms.match_id = target_match_id
    and ms.team_id = target_team_id
  limit 1;


  if existing_selection_id is not null then
    return existing_selection_id;
  end if;


  insert into public.match_selections (
    match_id,
    team_id,
    status,
    created_by,
    created_at,
    updated_by,
    updated_at
  )
  values (
    target_match_id,
    target_team_id,
    'Draft',
    current_user_id,
    now(),
    current_user_id,
    now()
  )
  returning selection_id
  into new_selection_id;


  return new_selection_id;
end;
$$;


-- ============================================================
-- 8. Add player to selection
-- ============================================================

create or replace function public.add_player_to_match_selection(
  target_selection_id bigint,
  target_player_id text,
  target_batting_position integer default null
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid;
  target_match_id text;
  target_team_id text;
  target_selection_status text;
  target_player_active boolean := false;
  new_selection_player_id bigint;
begin
  current_user_id := auth.uid();


  if current_user_id is null then
    raise exception 'Authentication required.';
  end if;


  if target_selection_id is null then
    raise exception 'Selection ID is required.';
  end if;


  if target_player_id is null
     or btrim(target_player_id) = '' then
    raise exception 'Player ID is required.';
  end if;


  if target_batting_position is not null
     and target_batting_position < 1 then
    raise exception
      'Batting position must be 1 or greater.';
  end if;


  select
    ms.match_id,
    ms.team_id,
    ms.status
  into
    target_match_id,
    target_team_id,
    target_selection_status
  from public.match_selections ms
  where ms.selection_id = target_selection_id
  for update;


  if not found then
    raise exception 'Match selection not found.';
  end if;


  if target_selection_status <> 'Draft' then
    raise exception
      'Only a draft selection can be edited.';
  end if;


  if not public.can_manage_match_selection(
    target_match_id,
    target_team_id
  ) then
    raise exception
      'You do not have permission to manage this selection.';
  end if;


  select p.active
  into target_player_active
  from public.players p
  where p.player_id = target_player_id;


  if not found then
    raise exception 'Player not found.';
  end if;


  if not coalesce(target_player_active, false) then
    raise exception
      'Only active DCC players can be selected.';
  end if;


  if exists (
    select 1
    from public.match_selection_players msp
    where msp.selection_id = target_selection_id
      and msp.player_id = target_player_id
  ) then
    raise exception
      'This player is already in the selection.';
  end if;


  if target_batting_position is not null
     and exists (
       select 1
       from public.match_selection_players msp
       where msp.selection_id = target_selection_id
         and msp.batting_position = target_batting_position
     ) then
    raise exception
      'That batting position is already assigned.';
  end if;


  insert into public.match_selection_players (
    selection_id,
    player_id,
    batting_position,
    is_captain,
    is_wicketkeeper,
    added_at,
    added_by,
    updated_at,
    updated_by
  )
  values (
    target_selection_id,
    target_player_id,
    target_batting_position,
    false,
    false,
    now(),
    current_user_id,
    now(),
    current_user_id
  )
  returning selection_player_id
  into new_selection_player_id;


  update public.match_selections
  set
    updated_by = current_user_id,
    updated_at = now()
  where selection_id = target_selection_id;


  return new_selection_player_id;
end;
$$;


-- ============================================================
-- 9. Remove player from selection
-- ============================================================

create or replace function public.remove_player_from_match_selection(
  target_selection_id bigint,
  target_player_id text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid;
  target_match_id text;
  target_team_id text;
  target_selection_status text;
begin
  current_user_id := auth.uid();


  if current_user_id is null then
    raise exception 'Authentication required.';
  end if;


  select
    ms.match_id,
    ms.team_id,
    ms.status
  into
    target_match_id,
    target_team_id,
    target_selection_status
  from public.match_selections ms
  where ms.selection_id = target_selection_id
  for update;


  if not found then
    raise exception 'Match selection not found.';
  end if;


  if target_selection_status <> 'Draft' then
    raise exception
      'Only a draft selection can be edited.';
  end if;


  if not public.can_manage_match_selection(
    target_match_id,
    target_team_id
  ) then
    raise exception
      'You do not have permission to manage this selection.';
  end if;


  if not exists (
    select 1
    from public.match_selection_players msp
    where msp.selection_id = target_selection_id
      and msp.player_id = target_player_id
  ) then
    raise exception
      'This player is not in the selection.';
  end if;


  delete from public.match_selection_players
  where selection_id = target_selection_id
    and player_id = target_player_id;


  update public.match_selections
  set
    updated_by = current_user_id,
    updated_at = now()
  where selection_id = target_selection_id;
end;
$$;


-- ============================================================
-- 10. Set batting position
-- ============================================================

create or replace function public.set_match_selection_batting_position(
  target_selection_id bigint,
  target_player_id text,
  target_batting_position integer default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid;
  target_match_id text;
  target_team_id text;
  target_selection_status text;
begin
  current_user_id := auth.uid();


  if current_user_id is null then
    raise exception 'Authentication required.';
  end if;


  if target_batting_position is not null
     and target_batting_position < 1 then
    raise exception
      'Batting position must be 1 or greater.';
  end if;


  select
    ms.match_id,
    ms.team_id,
    ms.status
  into
    target_match_id,
    target_team_id,
    target_selection_status
  from public.match_selections ms
  where ms.selection_id = target_selection_id
  for update;


  if not found then
    raise exception 'Match selection not found.';
  end if;


  if target_selection_status <> 'Draft' then
    raise exception
      'Only a draft selection can be edited.';
  end if;


  if not public.can_manage_match_selection(
    target_match_id,
    target_team_id
  ) then
    raise exception
      'You do not have permission to manage this selection.';
  end if;


  if not exists (
    select 1
    from public.match_selection_players msp
    where msp.selection_id = target_selection_id
      and msp.player_id = target_player_id
  ) then
    raise exception
      'This player is not in the selection.';
  end if;


  if target_batting_position is not null
     and exists (
       select 1
       from public.match_selection_players msp
       where msp.selection_id = target_selection_id
         and msp.batting_position = target_batting_position
         and msp.player_id <> target_player_id
     ) then
    raise exception
      'That batting position is already assigned.';
  end if;


  update public.match_selection_players
  set
    batting_position = target_batting_position,
    updated_at = now(),
    updated_by = current_user_id
  where selection_id = target_selection_id
    and player_id = target_player_id;


  update public.match_selections
  set
    updated_by = current_user_id,
    updated_at = now()
  where selection_id = target_selection_id;
end;
$$;


-- ============================================================
-- 11. Set captain
-- ============================================================

create or replace function public.set_match_selection_captain(
  target_selection_id bigint,
  target_player_id text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid;
  target_match_id text;
  target_team_id text;
  target_selection_status text;
begin
  current_user_id := auth.uid();


  if current_user_id is null then
    raise exception 'Authentication required.';
  end if;


  select
    ms.match_id,
    ms.team_id,
    ms.status
  into
    target_match_id,
    target_team_id,
    target_selection_status
  from public.match_selections ms
  where ms.selection_id = target_selection_id
  for update;


  if not found then
    raise exception 'Match selection not found.';
  end if;


  if target_selection_status <> 'Draft' then
    raise exception
      'Only a draft selection can be edited.';
  end if;


  if not public.can_manage_match_selection(
    target_match_id,
    target_team_id
  ) then
    raise exception
      'You do not have permission to manage this selection.';
  end if;


  if not exists (
    select 1
    from public.match_selection_players msp
    where msp.selection_id = target_selection_id
      and msp.player_id = target_player_id
  ) then
    raise exception
      'Captain must be a selected player.';
  end if;


  update public.match_selection_players
  set
    is_captain = false,
    updated_at = now(),
    updated_by = current_user_id
  where selection_id = target_selection_id
    and is_captain = true;


  update public.match_selection_players
  set
    is_captain = true,
    updated_at = now(),
    updated_by = current_user_id
  where selection_id = target_selection_id
    and player_id = target_player_id;


  update public.match_selections
  set
    updated_by = current_user_id,
    updated_at = now()
  where selection_id = target_selection_id;
end;
$$;


-- ============================================================
-- 12. Set wicketkeeper
-- ============================================================

create or replace function public.set_match_selection_wicketkeeper(
  target_selection_id bigint,
  target_player_id text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid;
  target_match_id text;
  target_team_id text;
  target_selection_status text;
begin
  current_user_id := auth.uid();


  if current_user_id is null then
    raise exception 'Authentication required.';
  end if;


  select
    ms.match_id,
    ms.team_id,
    ms.status
  into
    target_match_id,
    target_team_id,
    target_selection_status
  from public.match_selections ms
  where ms.selection_id = target_selection_id
  for update;


  if not found then
    raise exception 'Match selection not found.';
  end if;


  if target_selection_status <> 'Draft' then
    raise exception
      'Only a draft selection can be edited.';
  end if;


  if not public.can_manage_match_selection(
    target_match_id,
    target_team_id
  ) then
    raise exception
      'You do not have permission to manage this selection.';
  end if;


  if not exists (
    select 1
    from public.match_selection_players msp
    where msp.selection_id = target_selection_id
      and msp.player_id = target_player_id
  ) then
    raise exception
      'Wicketkeeper must be a selected player.';
  end if;


  update public.match_selection_players
  set
    is_wicketkeeper = false,
    updated_at = now(),
    updated_by = current_user_id
  where selection_id = target_selection_id
    and is_wicketkeeper = true;


  update public.match_selection_players
  set
    is_wicketkeeper = true,
    updated_at = now(),
    updated_by = current_user_id
  where selection_id = target_selection_id
    and player_id = target_player_id;


  update public.match_selections
  set
    updated_by = current_user_id,
    updated_at = now()
  where selection_id = target_selection_id;
end;
$$;


-- ============================================================
-- 13. Publish selection
-- ============================================================
--
-- Publication deliberately does NOT check availability.
--
-- It also deliberately does not require exactly 11 players.
-- Real cricket can involve reduced teams, unusual formats and
-- administrative corrections.
--
-- A captain and wicketkeeper ARE required before publication.
-- ============================================================

create or replace function public.publish_match_selection(
  target_selection_id bigint
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid;
  target_match_id text;
  target_team_id text;
  target_selection_status text;
  target_match_status text;
  selected_player_count integer;
  captain_count integer;
  wicketkeeper_count integer;
begin
  current_user_id := auth.uid();


  if current_user_id is null then
    raise exception 'Authentication required.';
  end if;


  select
    ms.match_id,
    ms.team_id,
    ms.status
  into
    target_match_id,
    target_team_id,
    target_selection_status
  from public.match_selections ms
  where ms.selection_id = target_selection_id
  for update;


  if not found then
    raise exception 'Match selection not found.';
  end if;


  if target_selection_status <> 'Draft' then
    raise exception
      'Only a draft selection can be published.';
  end if;


  if not public.can_manage_match_selection(
    target_match_id,
    target_team_id
  ) then
    raise exception
      'You do not have permission to publish this selection.';
  end if;


  select m.status
  into target_match_status
  from public.matches m
  where m.match_id = target_match_id;


  if not found then
    raise exception 'Match not found.';
  end if;


  if target_match_status <> 'Scheduled' then
    raise exception
      'Selection can only be published while the match is scheduled.';
  end if;


  select
    count(*),
    count(*) filter (where msp.is_captain = true),
    count(*) filter (where msp.is_wicketkeeper = true)
  into
    selected_player_count,
    captain_count,
    wicketkeeper_count
  from public.match_selection_players msp
  where msp.selection_id = target_selection_id;


  if selected_player_count = 0 then
    raise exception
      'At least one player must be selected before publication.';
  end if;


  if captain_count <> 1 then
    raise exception
      'Exactly one selected player must be designated captain.';
  end if;


  if wicketkeeper_count <> 1 then
    raise exception
      'Exactly one selected player must be designated wicketkeeper.';
  end if;


  update public.match_selections
  set
    status = 'Published',
    published_by = current_user_id,
    published_at = now(),
    updated_by = current_user_id,
    updated_at = now()
  where selection_id = target_selection_id;
end;
$$;


-- ============================================================
-- 14. Return published selection to Draft
-- ============================================================
--
-- Real cricket changes.
--
-- Somebody may drop out after the XI has been published.
-- An authorised administrator can return it to Draft, edit it,
-- and publish again.
-- ============================================================

create or replace function public.reopen_match_selection(
  target_selection_id bigint
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid;
  target_match_id text;
  target_team_id text;
  target_selection_status text;
  target_match_status text;
begin
  current_user_id := auth.uid();


  if current_user_id is null then
    raise exception 'Authentication required.';
  end if;


  select
    ms.match_id,
    ms.team_id,
    ms.status
  into
    target_match_id,
    target_team_id,
    target_selection_status
  from public.match_selections ms
  where ms.selection_id = target_selection_id
  for update;


  if not found then
    raise exception 'Match selection not found.';
  end if;


  if not public.can_manage_match_selection(
    target_match_id,
    target_team_id
  ) then
    raise exception
      'You do not have permission to manage this selection.';
  end if;


  if target_selection_status <> 'Published' then
    raise exception
      'Only a published selection can be returned to Draft.';
  end if;


  select m.status
  into target_match_status
  from public.matches m
  where m.match_id = target_match_id;


  if not found then
    raise exception 'Match not found.';
  end if;


  if target_match_status <> 'Scheduled' then
    raise exception
      'Selection can only be changed while the match is scheduled.';
  end if;


  update public.match_selections
  set
    status = 'Draft',
    published_by = null,
    published_at = null,
    updated_by = current_user_id,
    updated_at = now()
  where selection_id = target_selection_id;
end;
$$;


-- ============================================================
-- 15. Function privileges
-- ============================================================

revoke all
on function public.can_manage_match_selection(text, text)
from public;

revoke all
on function public.create_match_selection(text, text)
from public;

revoke all
on function public.add_player_to_match_selection(bigint, text, integer)
from public;

revoke all
on function public.remove_player_from_match_selection(bigint, text)
from public;

revoke all
on function public.set_match_selection_batting_position(bigint, text, integer)
from public;

revoke all
on function public.set_match_selection_captain(bigint, text)
from public;

revoke all
on function public.set_match_selection_wicketkeeper(bigint, text)
from public;

revoke all
on function public.publish_match_selection(bigint)
from public;

revoke all
on function public.reopen_match_selection(bigint)
from public;


grant execute
on function public.can_manage_match_selection(text, text)
to authenticated;

grant execute
on function public.create_match_selection(text, text)
to authenticated;

grant execute
on function public.add_player_to_match_selection(bigint, text, integer)
to authenticated;

grant execute
on function public.remove_player_from_match_selection(bigint, text)
to authenticated;

grant execute
on function public.set_match_selection_batting_position(bigint, text, integer)
to authenticated;

grant execute
on function public.set_match_selection_captain(bigint, text)
to authenticated;

grant execute
on function public.set_match_selection_wicketkeeper(bigint, text)
to authenticated;

grant execute
on function public.publish_match_selection(bigint)
to authenticated;

grant execute
on function public.reopen_match_selection(bigint)
to authenticated;