-- ============================================================
-- Add scheduled-match management to the canonical DCC match
-- lifecycle.
--
-- Purpose:
--   Allow public.matches to represent a match from the moment it
--   is scheduled, through availability / selection / match day,
--   and finally into the existing completed-match workflows.
--
-- This migration also introduces match-specific administration
-- for DCC-created Friendly, Warm-up and Internal matches.
--
-- Existing Official Season / imported match behaviour remains
-- unchanged.
--
-- Important:
--   - A fixture is a canonical match with status = 'Scheduled'.
--   - There is deliberately no separate fixtures table.
--   - Official Season matches cannot be created through the
--     ad-hoc DCC match creation function.
--   - Match-specific authority does not alter permanent Team
--     Admin assignments.
-- ============================================================


-- ============================================================
-- Extend canonical matches
--
-- Existing historical rows remain valid because all new columns
-- are nullable or have safe defaults.
-- ============================================================

alter table public.matches
add column start_datetime timestamp with time zone;

alter table public.matches
add column venue_name text;

alter table public.matches
add column home_away text;

alter table public.matches
add column created_by uuid
  references auth.users(id);

alter table public.matches
add column updated_at timestamp with time zone
  not null
  default now();


alter table public.matches
add constraint matches_home_away_check
check (
  home_away is null
  or home_away in (
    'Home',
    'Away',
    'Neutral'
  )
);


create index matches_start_datetime_idx
on public.matches (
  start_datetime
);


create index matches_status_start_datetime_idx
on public.matches (
  status,
  start_datetime
);


-- ============================================================
-- Match-specific administrators
--
-- These assignments grant authority over one particular match.
--
-- Primary use:
--   An active Team Admin creates an ad-hoc Friendly, Warm-up or
--   Internal match and automatically receives authority to
--   administer that match.
--
-- Historical assignments are preserved when removed.
-- ============================================================

create table public.match_admin_assignments (
  assignment_id bigint
    generated by default as identity
    primary key,

  match_id text
    not null
    references public.matches(match_id),

  user_id uuid
    not null
    references auth.users(id),

  active boolean
    not null
    default true,

  assigned_at timestamp with time zone
    not null
    default now(),

  assigned_by uuid
    not null
    references auth.users(id),

  removed_at timestamp with time zone,

  removed_by uuid
    references auth.users(id),

  created_at timestamp with time zone
    not null
    default now(),

  constraint match_admin_assignments_removal_state_check
    check (
      (
        active = true
        and removed_at is null
        and removed_by is null
      )
      or
      (
        active = false
        and removed_at is not null
        and removed_by is not null
      )
    )
);


create unique index match_admin_assignments_one_active_assignment
on public.match_admin_assignments (
  match_id,
  user_id
)
where active = true;


create index match_admin_assignments_match_active_idx
on public.match_admin_assignments (
  match_id,
  active
);


create index match_admin_assignments_user_active_idx
on public.match_admin_assignments (
  user_id,
  active
);


-- ============================================================
-- Row Level Security
--
-- Direct writes are not permitted. Match-admin assignments are
-- managed through controlled database functions.
-- ============================================================

alter table public.match_admin_assignments
enable row level security;


create policy
  "Active DCC users can read match admin assignments"
on public.match_admin_assignments
for select
to authenticated
using (
  exists (
    select 1
    from public.user_profiles
    where user_profiles.user_id = auth.uid()
      and user_profiles.status = 'Active'
  )
);


-- ============================================================
-- Helper: active Team Admin anywhere in DCC
--
-- Ad-hoc matches can arise independently of a Team Admin's
-- normal team assignment. Therefore any active Team Admin may
-- create a DCC Friendly / Warm-up / Internal match.
--
-- A Super Admin is also authorised.
-- ============================================================

create or replace function public.can_create_ad_hoc_dcc_match()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select
    auth.uid() is not null
    and exists (
      select 1
      from public.user_profiles
      where user_profiles.user_id = auth.uid()
        and user_profiles.status = 'Active'
        and (
          user_profiles.account_role = 'Super Admin'
          or exists (
            select 1
            from public.team_admin_assignments
            where team_admin_assignments.user_id = auth.uid()
              and team_admin_assignments.active = true
          )
        )
    );
$$;


-- ============================================================
-- Helper: manage one canonical match
--
-- Super Admin:
--   may manage any match.
--
-- Active match-specific administrator:
--   may manage the match to which they are actively assigned.
--
-- Existing import-review authority remains separate and is not
-- replaced by this helper.
-- ============================================================

create or replace function public.can_manage_match(
  target_match_id text
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select
    auth.uid() is not null
    and nullif(trim(target_match_id), '') is not null
    and exists (
      select 1
      from public.user_profiles
      where user_profiles.user_id = auth.uid()
        and user_profiles.status = 'Active'
        and (
          user_profiles.account_role = 'Super Admin'
          or exists (
            select 1
            from public.match_admin_assignments
            where match_admin_assignments.match_id =
                trim(target_match_id)
              and match_admin_assignments.user_id =
                auth.uid()
              and match_admin_assignments.active = true
          )
        )
    );
$$;


-- ============================================================
-- Create an ad-hoc DCC match
--
-- Allowed categories:
--   Friendly
--   Warm-up
--   Internal
--
-- Official Season is deliberately prohibited.
--
-- The creator automatically receives an active match-specific
-- admin assignment.
--
-- match_id is generated server-side so callers cannot choose or
-- collide with canonical identifiers.
-- ============================================================

create or replace function public.create_ad_hoc_dcc_match(
  target_season integer,
  target_match_date date,
  target_start_datetime timestamp with time zone,
  target_fixture_label text,
  target_stats_category text,
  target_venue_name text default null,
  target_home_away text default null
)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  new_match_id text;
  clean_fixture_label text;
  clean_stats_category text;
  clean_venue_name text;
  clean_home_away text;
begin
  -- ----------------------------------------------------------
  -- Authentication / authority
  -- ----------------------------------------------------------

  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  if not public.can_create_ad_hoc_dcc_match() then
    raise exception
      'You are not authorised to create an ad-hoc DCC match';
  end if;


  -- ----------------------------------------------------------
  -- Validate season
  -- ----------------------------------------------------------

  if target_season is null then
    raise exception 'A season is required';
  end if;

  perform 1
  from public.seasons
  where season = target_season;

  if not found then
    raise exception
      'Season % does not exist',
      target_season;
  end if;


  -- ----------------------------------------------------------
  -- Validate fixture date / time
  -- ----------------------------------------------------------

  if target_match_date is null then
    raise exception 'A match date is required';
  end if;

  if target_start_datetime is not null
     and target_start_datetime::date <>
       target_match_date then
    raise exception
      'Match date must match the supplied start date';
  end if;


  -- ----------------------------------------------------------
  -- Validate fixture label
  -- ----------------------------------------------------------

  clean_fixture_label :=
    nullif(trim(target_fixture_label), '');

  if clean_fixture_label is null then
    raise exception 'A fixture label is required';
  end if;


  -- ----------------------------------------------------------
  -- Validate category
  --
  -- Never permit Official Season through this function.
  -- ----------------------------------------------------------

  clean_stats_category :=
    nullif(trim(target_stats_category), '');

  if clean_stats_category is null then
    raise exception 'A match category is required';
  end if;

  if clean_stats_category not in (
    'Friendly',
    'Warm-up',
    'Internal'
  ) then
    raise exception
      'Ad-hoc DCC matches must be Friendly, Warm-up or Internal';
  end if;


  -- ----------------------------------------------------------
  -- Validate optional venue / home-away information
  -- ----------------------------------------------------------

  clean_venue_name :=
    nullif(trim(target_venue_name), '');

  clean_home_away :=
    nullif(trim(target_home_away), '');

  if clean_home_away is not null
     and clean_home_away not in (
       'Home',
       'Away',
       'Neutral'
     ) then
    raise exception
      'Home/away value must be Home, Away or Neutral';
  end if;


  -- ----------------------------------------------------------
  -- Generate canonical match id.
  --
  -- Use UUID text so creation does not depend on client-side
  -- identifiers or the naming convention of imported matches.
  -- ----------------------------------------------------------

  new_match_id :=
    gen_random_uuid()::text;


  -- ----------------------------------------------------------
  -- Create canonical scheduled match
  --
  -- Friendly / Warm-up / Internal matches are explicitly
  -- excluded from Official Season statistics.
  --
  -- Internal is also reflected through the existing dedicated
  -- boolean for compatibility with current canonical data.
  -- ----------------------------------------------------------

  insert into public.matches (
    match_id,
    season,
    match_date,
    start_datetime,
    fixture_label,
    status,
    is_internal_dcc_match,
    stats_category,
    official_season_eligible,
    venue_name,
    home_away,
    created_by,
    updated_at
  )
  values (
    new_match_id,
    target_season,
    target_match_date,
    target_start_datetime,
    clean_fixture_label,
    'Scheduled',
    clean_stats_category = 'Internal',
    clean_stats_category,
    false,
    clean_venue_name,
    clean_home_away,
    auth.uid(),
    now()
  );


  -- ----------------------------------------------------------
  -- Give the creator match-specific administrative authority.
  -- ----------------------------------------------------------

  insert into public.match_admin_assignments (
    match_id,
    user_id,
    active,
    assigned_at,
    assigned_by
  )
  values (
    new_match_id,
    auth.uid(),
    true,
    now(),
    auth.uid()
  );


  return new_match_id;
end;
$$;


-- ============================================================
-- Assign another match administrator
--
-- Existing match authority is required.
--
-- Only an active DCC account may be assigned.
--
-- This is intentionally match-specific. It does not create or
-- modify permanent Team Admin assignments.
-- ============================================================

create or replace function public.add_match_admin(
  target_match_id text,
  target_user_id uuid
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  new_assignment_id bigint;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  if nullif(trim(target_match_id), '') is null then
    raise exception 'A match is required';
  end if;

  if target_user_id is null then
    raise exception 'A user is required';
  end if;


  perform 1
  from public.matches
  where match_id = trim(target_match_id);

  if not found then
    raise exception
      'Match % does not exist',
      trim(target_match_id);
  end if;


  if not public.can_manage_match(
    trim(target_match_id)
  ) then
    raise exception
      'You are not authorised to manage this match';
  end if;


  perform 1
  from public.user_profiles
  where user_id = target_user_id
    and status = 'Active';

  if not found then
    raise exception
      'The selected user does not have an active DCC account';
  end if;


  perform 1
  from public.match_admin_assignments
  where match_id = trim(target_match_id)
    and user_id = target_user_id
    and active = true;

  if found then
    raise exception
      'The selected user is already an active administrator for this match';
  end if;


  insert into public.match_admin_assignments (
    match_id,
    user_id,
    active,
    assigned_at,
    assigned_by
  )
  values (
    trim(target_match_id),
    target_user_id,
    true,
    now(),
    auth.uid()
  )
  returning assignment_id
  into new_assignment_id;

  return new_assignment_id;
end;
$$;


-- ============================================================
-- Remove a match administrator
--
-- Historical assignment is closed rather than deleted.
--
-- A user cannot remove their own active assignment through this
-- function. This prevents the last working administrator from
-- accidentally removing their own authority. Super Admin retains
-- global authority independently of match assignments.
-- ============================================================

create or replace function public.remove_match_admin(
  target_match_id text,
  target_user_id uuid
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_assignment_id bigint;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  if nullif(trim(target_match_id), '') is null then
    raise exception 'A match is required';
  end if;

  if target_user_id is null then
    raise exception 'A user is required';
  end if;


  if not public.can_manage_match(
    trim(target_match_id)
  ) then
    raise exception
      'You are not authorised to manage this match';
  end if;


  if target_user_id = auth.uid() then
    raise exception
      'You cannot remove your own match administrator assignment';
  end if;


  select assignment_id
  into target_assignment_id
  from public.match_admin_assignments
  where match_id = trim(target_match_id)
    and user_id = target_user_id
    and active = true
  for update;

  if not found then
    raise exception
      'The selected user is not an active administrator for this match';
  end if;


  update public.match_admin_assignments
  set
    active = false,
    removed_at = now(),
    removed_by = auth.uid()
  where assignment_id = target_assignment_id;
end;
$$;


-- ============================================================
-- Table permissions
--
-- Preserve the existing public.matches permission model.
-- This migration does NOT grant direct writes to matches.
--
-- match_admin_assignments is readable only by authenticated
-- users, with RLS further requiring an Active DCC account.
--
-- All assignment mutations use controlled functions.
-- ============================================================

revoke all
on table public.match_admin_assignments
from public;

revoke all
on table public.match_admin_assignments
from anon;

revoke all
on table public.match_admin_assignments
from authenticated;

grant select
on table public.match_admin_assignments
to authenticated;


-- ============================================================
-- Function permissions
-- ============================================================

revoke all
on function public.can_create_ad_hoc_dcc_match()
from public;

grant execute
on function public.can_create_ad_hoc_dcc_match()
to authenticated;


revoke all
on function public.can_manage_match(text)
from public;

grant execute
on function public.can_manage_match(text)
to authenticated;


revoke all
on function public.create_ad_hoc_dcc_match(
  integer,
  date,
  timestamp with time zone,
  text,
  text,
  text,
  text
)
from public;

grant execute
on function public.create_ad_hoc_dcc_match(
  integer,
  date,
  timestamp with time zone,
  text,
  text,
  text,
  text
)
to authenticated;


revoke all
on function public.add_match_admin(
  text,
  uuid
)
from public;

grant execute
on function public.add_match_admin(
  text,
  uuid
)
to authenticated;


revoke all
on function public.remove_match_admin(
  text,
  uuid
)
from public;

grant execute
on function public.remove_match_admin(
  text,
  uuid
)
to authenticated;